os: osx
sudo: false
language: node_js
cache:
  directories:
  - node_modules

node_js:
  - '4'
  - '5'
  - '6'
  - '7'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn --version
  - yarn run ci
